server:
  port: 9003

spring:
  application:
    name: codeworld-cloud-marketing
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/codeworld-cloud-shop?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: true
        weight: 1
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 5
    host: 192.168.2.4
  rabbitmq:
    virtual-host: /codeworld-shop
    host: 192.168.2.2
    username: feicheng
    password: mengli090420
    template:
      exchange: CODEWORLD-SHOP.EXCHANGE #默认交换机CODEWORLD-SHOP.EXCHANGE
mybatis:
  mapper-locations: classpath:mapper/*.xml
codeworld:
  jwt:
    secret: codeworld@Login(Auth}*^31)&codeworld% # 用于生存rsa公钥和私钥的密文,越复杂越好
    pubKeyPath: D:\\temp\\rsa\\rsa.pub # 公钥地址
    priKeyPath: D:\\temp\\rsa\\rsa.pri # 私钥地址
    expire: 30   # 过期时间,单位分钟
    cookieMaxAge: 1800
    cookieName: token

logging:
  config: classpath:log/logback-spring.xml

xxl:
  job:
    accessToken:
    admin:
      addresses: http://localhost:9999/xxl-job-admin
    executor:
      address:
      appname: xxl-job-marketing
      ip:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9004
