server:
  port: 6001

spring:
  application:
    name: codeworld-cloud-upload
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: true
        weight: 1
